# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titleSlug',
            new_name='postSlug',
        ),
    ]
