
# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 05:55
from __future__ import unicode_literals

from django.db import migrations
from django.db import migrations, models
import mptt.fields
import django.db.models.deletion
import django.utils.timezone
import mptt

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
 migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50,null=True, unique=True),
        ),        	

    ]
