# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='summary',
            new_name='asummary',
        ),
    ]
