# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parentSlug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
