# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180409_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='asummary',
            new_name='summary',
        ),
    ]
