# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 06:06
from __future__ import unicode_literals
from django.db import migrations, models
import mptt.fields
import django.db.models.deletion
import django.utils.timezone
import mptt
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180410_0655'),
    ]

    operations = [
	migrations.AddField(
            model_name="category",
            name="parent_id",
            field=models.IntegerField(null=True),
	),
    ]
