# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20171107_1816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='category_tag',
        ),
        migrations.AlterField(
            model_name='comment',
            name='belongs_to_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
