# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171107_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='belongs_to_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_tag',
        ),
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
