# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
