# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20171108_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='category_tag',
            field=models.ManyToManyField(to='posts.category'),
        ),
    ]
