# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary1',
            field=models.CharField(default=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='summary2',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
