# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20171108_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
