# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180409_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='summary1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='summary2',
        ),
    ]
