# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_category_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post_tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='category_tag',
            field=models.ManyToManyField(to='posts.category'),
        ),
    ]
