# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 07:21
from __future__ import unicode_literals
from django.db import migrations, models
import mptt.fields
import django.db.models.deletion
import django.utils.timezone
import mptt

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180410_0812'),
    ]

    operations = [
migrations.AddField(
            model_name="post",
            name="category_id",
            field=models.IntegerField(null=True)
        ),
    ]
