# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 07:31
from __future__ import unicode_literals
from django.db import migrations, models
import mptt.fields
import django.db.models.deletion
import django.utils.timezone
import mptt

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180410_0821'),
    ]

    operations = [
	migrations.AlterField(
		model_name="Category",
		name = "level",
		field = models.PositiveIntegerField(null=True, default=0, db_index=True, editable=False),
),
    ]
