# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 07:49
from __future__ import unicode_literals
from django.db import migrations, models
import mptt.fields
import django.db.models.deletion
import django.utils.timezone
import mptt
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180410_0831'),
    ]

    operations = [
	migrations.AlterField(
		model_name="Category",
		name="lft",
		field=models.PositiveIntegerField(null=True, db_index=True, editable=False, default=0),
		),
	migrations.AlterField(
                model_name="Category",
                name="rght",
                field=models.PositiveIntegerField(null=True, db_index=True, default=0, editable=False),
		),
    
    ]
