# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 08:28
from __future__ import unicode_literals
from django.db import migrations, models
import mptt.fields
import django.db.models.deletion
import django.utils.timezone
from mptt.models import *

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20180410_0849'),
    ]

    operations = [
	migrations.AlterField(
	model_name="Category",
	name = "parent",
	field = TreeForeignKey('self', null=True, blank=True, 
        related_name='children', db_index=True ), ),
    ]
