# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 09:02
from __future__ import unicode_literals

from django.db import migrations
from django.db import migrations, models
import mptt.fields
import django.db.models.deletion
import django.utils.timezone
import mptt

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_post_category'),
    ]

    operations = [
		     migrations.AddField(
                model_name="Post",
                name = "Category",
                field =  models.ForeignKey('Category', null=True, blank=True),
),
    ]
