# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20180410_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Category',
        ),
    ]
