# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 09:04
from __future__ import unicode_literals
from django.db import migrations, models
import mptt.fields
import django.utils.timezone
import mptt

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_post_category'),
    ]

    operations = [
migrations.AddField(
                model_name="Post",
                name = "Category",
                field =  models.ForeignKey('Category', null=True, blank=True)
),

    ]
