# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20171115_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Cat_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='posts.Category'),
        ),
    ]
