# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0062_auto_20171130_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='authorSlug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='titleSlug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='posts.Category'),
        ),
    ]
