# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0109_auto_20180207_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postimage1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postimage2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postimage3',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='posts.Category'),
        ),
    ]
