# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0111_auto_20180216_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mainimage',
        ),
        migrations.AddField(
            model_name='post',
            name='editedimage',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='posts.Category'),
        ),
    ]
