# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0113_auto_20180222_0442'),
        ('posts', '0112_auto_20180218_1007'),
    ]

    operations = [
    ]
