# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0115_auto_20180222_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='posts.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='editedimage',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
