# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0117_auto_20180222_1220'),
        ('posts', '0115_auto_20180222_1219'),
    ]

    operations = [
    ]
