# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0118_auto_20180225_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='editedimage',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='posts.Category'),
        ),
    ]
