# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0119_auto_20180226_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editedimage',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='posts.Category'),
        ),
    ]
