# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0116_auto_20180224_1927'),
        ('posts', '0128_auto_20180224_1930'),
    ]

    operations = [
    ]
