# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-25 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0117_auto_20180224_1942'),
        ('posts', '0130_auto_20180224_1932'),
    ]

    operations = [
    ]
