# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0131_merge_20180225_0654'),
        ('posts', '0121_auto_20180227_0845'),
    ]

    operations = [
    ]
