# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-05 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0123_auto_20180227_1739'),
        ('posts', '0133_auto_20180227_0854'),
    ]

    operations = [
    ]
