# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0134_merge_20180305_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_in_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='posts.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='editedimage',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='primary_images'),
        ),
    ]
