# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0135_auto_20180311_0931'),
        ('posts', '0139_auto_20180311_1154'),
    ]

    operations = [
    ]
