# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0139_auto_20180311_1154'),
        ('posts', '0134_merge_20180311_0927'),
    ]

    operations = [
    ]
